stages:
  - compute
  - process
  - tex

variables:
  DIJITSO_CACHE_DIR: $CI_PROJECT_DIR/.cache/dijitso
  GIT_STRATEGY: fetch

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .cache/dijitso
    - numericals/zeroguess
    - numericals/rampdown
    - numericals/rampdown-noopt
    - plots/coefficients
    - plots/optimized
    - tables


numericals:
  stage: compute
  image: optipulsproject/optipuls
  script: make numericals.all
  artifacts:
    paths:
      - numericals/zeroguess
      - numericals/rampdown
      - numericals/rampdown-noopt

plots:
  stage: process
  image: optipulsproject/optipuls
  script: make plots.all
  artifacts:
    paths:
      - plots/coefficients
      - plots/optimized

tables:
  stage: process
  image: optipulsproject/tabulate
  script: make tables.all
  artifacts:
    paths:
      - tables/zeroguess.tex
      - tables/rampdown.tex

tex:
  stage: tex
  image: optipulsproject/publications
  script: make slides
  artifacts:
    paths:
      - slides-bayreuth.pdf
